---
epochs: 5
lr: 0.0005
train_ratio: 0.8
root_folder: hcrl_sa
batch_size: 512
momentum: 0.9
datasize: 1.0
optimizer: torch.optim.SGD
_target_: trainers.DistillationTrainer
device: cuda
use_focal_loss: true
profile: false

# Fusion-specific parameters
fusion_episodes: 50        # Number of fusion training episodes
max_train_samples: 25000   # Limit training samples for memory
max_val_samples: 5000      # Limit validation samples
alpha_steps: 21            # Number of fusion weight steps
fusion_lr: 0.001          # Fusion agent learning rate
fusion_epsilon: 0.3        # Initial exploration rate
fusion_buffer_size: 10000  # Experience replay buffer size
fusion_batch_size: 64        # Smaller batch size
fusion_target_update: 100    # More frequent target updates