# Lightning training configuration
mode: "lightning"
description: "Standard Lightning training with auto-optimization"

# Learning parameters
learning_rate: 0.001
weight_decay: 1e-4
scheduler: "cosine"              # cosine, step, plateau, linear

# Training behavior
batch_size: auto                 # auto for Lightning Tuner, or specific size
accumulate_grad_batches: 1       # For simulating larger batches
gradient_clip_val: 1.0
early_stopping:
  patience: 10
  min_delta: 0.001

# Data loading
num_workers: auto                # auto = detected cores, or specific number
persistent_workers: true         # Keep workers alive between epochs
pin_memory: true                # Faster GPU transfer

# Validation settings
val_check_interval: 1.0          # Check every epoch (1.0) or fraction
limit_val_batches: 1.0          # Use all validation data

# Callbacks
callbacks:
  enable_checkpoint: true
  enable_early_stopping: true
  enable_model_summary: true
  enable_progress_bar: true