# Quick development and testing configuration
mode: "quickstart"
description: "Fast training for development and debugging"

# Fast training parameters
learning_rate: 0.01            # Higher LR for quick convergence
weight_decay: 0.0              # No regularization for speed
scheduler: null                # No scheduling for simplicity

# Small batch configuration
batch_size: 256                # Small batches for speed
accumulate_grad_batches: 1
gradient_clip_val: null        # No clipping for speed

# Minimal epochs for testing
max_epochs: 10                 # Quick training
fast_dev_run: false            # Set to true for single batch test

# Data loading (minimal workers for debugging)
dataloader:
  num_workers: 0               # Single-threaded for debugging
  persistent_workers: false
  pin_memory: false
  shuffle_train: false         # Reproducible order

# Debug settings
debug:
  limit_train_batches: 0.1     # Only use 10% of training data
  limit_val_batches: 0.1       # Only use 10% of validation data
  overfit_batches: 0           # Set > 0 to overfit on small subset
  
# Minimal callbacks
callbacks:
  model_checkpoint:
    save_top_k: 1
    monitor: "train_loss"
    mode: "min"
  early_stopping:
    enabled: false             # No early stopping for quick tests

# Verbose logging for debugging  
logging:
  level: DEBUG
  log_every_n_steps: 1         # Log every step
  enable_model_summary: true